
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: alb-controller
    meta.helm.sh/release-namespace: ic-aks
  creationTimestamp: "2024-06-12T07:57:03Z"
  generation: 1
  labels:
    app: alb-controller
    app.kubernetes.io/managed-by: Helm
  name: alb-controller
  namespace: azure-alb-system
  resourceVersion: "17229"
  uid: 34e6ccca-c896-49ca-aad4-d246936f40a2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alb-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8001"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: alb-controller
        azure.workload.identity/use: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - alb-controller
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - --log-level
        - info
        - --namespace
        - test-infra
        command:
        - /alb-controller
        env:
        - name: AZURE_CLIENT_ID
          value: 24dca052-9ec8-4166-8f5d-85ab9c61abaf
        image: mcr.microsoft.com/application-lb/images/alb-controller:1.0.2
        imagePullPolicy: IfNotPresent
        name: alb-controller
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8001
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - curl
        - http://alb-controller-bootstrap.azure-alb-system.svc.cluster.local:9005/healthz
        - --connect-timeout
        - "2"
        - --retry
        - "50"
        - --retry-connrefused
        - --retry-delay
        - "5"
        image: mcr.microsoft.com/aks/devinfra/base-os-runtime-curl:master.220112.2
        imagePullPolicy: IfNotPresent
        name: init-alb-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: alb-controller-sa
      serviceAccountName: alb-controller-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 6000

