[
    {
        "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12",
        "repository_url": "https://api.github.com/repos/fbisceglia02/AzureOps",
        "labels_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12/labels{/name}",
        "comments_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12/comments",
        "events_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12/events",
        "html_url": "https://github.com/fbisceglia02/AzureOps/issues/12",
        "id": 2172615631,
        "node_id": "I_kwDOLIfWZ86Bf3vP",
        "number": 12,
        "title": "Power Automate: arma segreta: the days in the month are not very aligned",
        "user": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-03-06T23:25:14Z",
        "updated_at": "2024-03-06T23:25:14Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
            "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/12/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11",
        "repository_url": "https://api.github.com/repos/fbisceglia02/AzureOps",
        "labels_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11/labels{/name}",
        "comments_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11/comments",
        "events_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11/events",
        "html_url": "https://github.com/fbisceglia02/AzureOps/issues/11",
        "id": 2152918844,
        "node_id": "I_kwDOLIfWZ86AUu88",
        "number": 11,
        "title": "Trigger infra eraser without retriggering any workflows to be set as the default value",
        "user": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "fbisceglia02",
                "id": 120172848,
                "node_id": "U_kgDOBymxMA",
                "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/fbisceglia02",
                "html_url": "https://github.com/fbisceglia02",
                "followers_url": "https://api.github.com/users/fbisceglia02/followers",
                "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
                "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
                "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
                "repos_url": "https://api.github.com/users/fbisceglia02/repos",
                "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
                "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-02-25T20:03:39Z",
        "updated_at": "2024-03-01T00:47:37Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": null,
        "reactions": {
            "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/11/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10",
        "repository_url": "https://api.github.com/repos/fbisceglia02/AzureOps",
        "labels_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10/labels{/name}",
        "comments_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10/comments",
        "events_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10/events",
        "html_url": "https://github.com/fbisceglia02/AzureOps/issues/10",
        "id": 2144048739,
        "node_id": "I_kwDOLIfWZ85_y5Zj",
        "number": 10,
        "title": "Make script executable from workflow run input",
        "user": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 6465463313,
                "node_id": "LA_kwDOLIfWZ88AAAABgV8kEQ",
                "url": "https://api.github.com/repos/fbisceglia02/AzureOps/labels/enhancement",
                "name": "enhancement",
                "color": "a2eeef",
                "default": true,
                "description": "New feature or request"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "fbisceglia02",
                "id": 120172848,
                "node_id": "U_kgDOBymxMA",
                "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/fbisceglia02",
                "html_url": "https://github.com/fbisceglia02",
                "followers_url": "https://api.github.com/users/fbisceglia02/followers",
                "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
                "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
                "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
                "repos_url": "https://api.github.com/users/fbisceglia02/repos",
                "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
                "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-02-20T10:28:47Z",
        "updated_at": "2024-02-20T10:28:47Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Scripts residing in AzureOps repository must be executed basing on inputs on the workflow.",
        "reactions": {
            "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/10/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    },
    {
        "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9",
        "repository_url": "https://api.github.com/repos/fbisceglia02/AzureOps",
        "labels_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9/labels{/name}",
        "comments_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9/comments",
        "events_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9/events",
        "html_url": "https://github.com/fbisceglia02/AzureOps/issues/9",
        "id": 2143880363,
        "node_id": "I_kwDOLIfWZ85_yQSr",
        "number": 9,
        "title": "pip-addr artifact file coming out empty",
        "user": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 6465463308,
                "node_id": "LA_kwDOLIfWZ88AAAABgV8kDA",
                "url": "https://api.github.com/repos/fbisceglia02/AzureOps/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": true,
                "description": "Something isn't working"
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": {
            "login": "fbisceglia02",
            "id": 120172848,
            "node_id": "U_kgDOBymxMA",
            "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/fbisceglia02",
            "html_url": "https://github.com/fbisceglia02",
            "followers_url": "https://api.github.com/users/fbisceglia02/followers",
            "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
            "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
            "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
            "repos_url": "https://api.github.com/users/fbisceglia02/repos",
            "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
            "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
            "type": "User",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "fbisceglia02",
                "id": 120172848,
                "node_id": "U_kgDOBymxMA",
                "avatar_url": "https://avatars.githubusercontent.com/u/120172848?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/fbisceglia02",
                "html_url": "https://github.com/fbisceglia02",
                "followers_url": "https://api.github.com/users/fbisceglia02/followers",
                "following_url": "https://api.github.com/users/fbisceglia02/following{/other_user}",
                "gists_url": "https://api.github.com/users/fbisceglia02/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/fbisceglia02/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fbisceglia02/subscriptions",
                "organizations_url": "https://api.github.com/users/fbisceglia02/orgs",
                "repos_url": "https://api.github.com/users/fbisceglia02/repos",
                "events_url": "https://api.github.com/users/fbisceglia02/events{/privacy}",
                "received_events_url": "https://api.github.com/users/fbisceglia02/received_events",
                "type": "User",
                "site_admin": false
            }
        ],
        "milestone": null,
        "comments": 0,
        "created_at": "2024-02-20T09:04:31Z",
        "updated_at": "2024-02-20T09:05:29Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "When downloading the artifact, pip-addr (the file where the public ip address must come out), cames out empty, so we can't ssh.\r\n",
        "reactions": {
            "url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/fbisceglia02/AzureOps/issues/9/timeline",
        "performed_via_github_app": null,
        "state_reason": null
    }
]
