name: Deploy ten VMs in a resource group for load testing
#comment
on:
  workflow_dispatch:
env:
  RESOURCE_GROUP: 'icmelrg'
jobs:
  create-rg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Custom Login
        shell: bash
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}        
      - name: Deploy resource group
        shell: bash
        run: az group create --name icmelrg --location eastus           
  deploy-vnets-vms:
    needs: create-rg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Azure Custom Login
      shell: bash
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}    
    - name: Deploy Infrastructure and Install Software
      shell: bash
      run: |        
        # -- Virtual Networks --           
        az network vnet create -g $RESOURCE_GROUP -n icvnet0 --address-prefix 10.0.0.0/16 --subnet-name icvnet0_sub --subnet-prefixes '10.0.0.0/24'          
        az network vnet create -g $RESOURCE_GROUP -n icvnet1 --address-prefix 10.1.0.0/16 --subnet-name icvnet1_sub --subnet-prefixes '10.1.0.0/24'
        # -- Deploy VMs and setup NPM and Artillery --
        for i in {0..9}; do
          vnet="icvnet$((i % 2))"
          subnet="${vnet}_sub"
          az vm create -n "icmel$i" -g $RESOURCE_GROUP --image Ubuntu2204 --vnet-name $vnet --subnet $subnet --admin-username azureuser --generate-ssh-keys --output json --verbose
          # Install Node.js and Artillery
          az vm run-command invoke -g $RESOURCE_GROUP -n "icmel$i" --command-id RunShellScript --scripts "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -; sudo apt-get install -y nodejs; sudo npm install -g npm@latest; sudo npm install -g artillery"
        done
