# Called Workflow - .github/workflows/called_workflow.yml
name: Called Workflow

on:
  repository_dispatch:
    types: [trigger-called-workflow, test]

jobs:
  respond_to_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script or command
        run: echo "Responding to repository dispatch event." 
      - name: Conditional Step
        # if: ${{ github.event.client_payload.condition == 'test' }}
        run: |
          echo "Payload Content: ${{ github.event.client_payload.connection }}"
