name: Connect and restart

on:
  workflow_dispatch:

jobs:
  connect-and-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Deploy Infrastructure
        shell: bash
        run: |
            # Create connections to the sechub
            vnets=("icvnet0" "icvnet1" "icnetappvnet")
            
            for vnet in "${vnets[@]}"
            do
                echo "Creating connection to the sechub VNET: $vnet"
                az network vhub connection create --name "icmel_${vnet}_conn" --resource-group $resource_group --vhub-name icmel_sechub --remote-vnet "$vnet"
            done
            
            
            # Restart these VMs
            vm_names=("icmel0" "icmel1" "icnetapp")
            
            # Loop through each VM name in the array and restart it
            for vm_name in "${vm_names[@]}"
            do
                echo "Restarting VM: $vm_name"
                az vm restart --name "$vm_name" --resource-group "$resource_group"
            done
        