name: Infrastructure Eraser

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'trigger other workflows after it'
        required: false
        type: choice
        options:
        - 'vm-vnet-ez'
      resource-group-name:
        type: string
        required: false
        description: 'Name of the resource group to erase, enter "clear-all" to clear them all'

jobs:
  erase-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Erase Infrastructure
        shell: bash
        run: |
          deleteResourceGroups() {
            local resourceGroup=$1
            if [ "$resourceGroup" = "clear-all" ] || [ -z "$resourceGroup" ]; then
              echo "Attempting to clear all resource groups..."
              local resourceGroupsToDelete=$(az group list | jq -r '.[].name | select(. != "--help" and . != "NetworkWatcherRG")')
              
              for name in $resourceGroupsToDelete; do
                if ! az group delete -n "$name" --yes; then
                  echo "Failed to delete Resource Group $name, retrying..."
                  deleteResourceGroups "$resourceGroup"
                  break
                else
                  echo "Deleted Resource Group $name"
                fi
              done
            else
              if ! az group delete -n "$resourceGroup" --yes; then
                echo "Failed to delete Resource Group $resourceGroup, retrying..."
                deleteResourceGroups "$resourceGroup"
              else
                echo "Deleted Resource Group $resourceGroup"
              fi
            fi
          } 
          resourceGroup="${{ github.event.inputs.resource-group-name }}"
          deleteResourceGroups "$resourceGroup"

      - name: Dispatch vm-vnet-ez workflow
        if: ${{ github.event.inputs.trigger == 'vm-vnet-ez' }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/fbisceglia02/AzureOps/dispatches \
            -d '{"event_type": "dispatch-vm-vnet-ez", "client_payload": {"connection": "artifacts"}}'