name: Infrastructure Eraser

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'trigger other workflows after it'
        required: false
        type: choice
        options:
        - 'none'
        - 'vm-vnet-ez'
        - 'two-vm-vnet'
      resource-group-name:
        type: string
        required: false
        description: 'Name of the resource group to erase, enter "clear-all" to clear them all'

jobs:
  erase-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.APP_REG_CLIENT_ID }} -p ${{ secrets.APP_REG_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Erase Infrastructure
        shell: bash
        run: |
          deleteResourceGroups() {
            local resourceGroup=$1
            if [ "$resourceGroup" = "clear-all" ]; then
              echo "Attempting to clear all resource groups..."
              local resourceGroupsToDelete=$(az group list | jq -r '.[].name | select(. != "--help" and . != "NetworkWatcherRG")')
              
              for name in $resourceGroupsToDelete; do
                if ! az group delete -n "$name" --yes; then
                  echo "Failed to delete Resource Group $name, retrying..."
                  deleteResourceGroups "$resourceGroup"
                  break
                else
                  echo "Deleted Resource Group $name"
                fi
              done
            else
              if ! az group delete -n "$resourceGroup" --yes; then
                echo "Failed to delete Resource Group $resourceGroup, retrying..."
                deleteResourceGroups "$resourceGroup"
              else
                echo "Deleted Resource Group $resourceGroup"
              fi
            fi
          } 
          resourceGroup="${{ github.event.inputs.resource-group-name }}"
          deleteResourceGroups "$resourceGroup"

      - name: Dispatch vm-vnet-ez workflow
        if: ${{ github.event.inputs.trigger == 'vm-vnet-ez' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: fbisceglia02/AzureOps
          event-type: "dispatch-vm-vnet-ez"
          client-payload: '{"connection": "artifacts"}'

      - name: Dispatch two-vm-vnet workflow
        if: ${{ github.event.inputs.trigger == 'two-vm-vnet' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: fbisceglia02/AzureOps
          event-type: "dispatch-two-vm-vnet"
          client-payload: '{"connection": "artifacts"}'

      - name: Send Completion message
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_API_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_API_KEY }}" \
            --form-string "message=Azure infrastructure erased" \
            https://api.pushover.net/1/messages.json
