name: Infrastructure Eraser

on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        type: string
        required: true
        description: 'Name of the resource group to erase, enter "clear-all" to clear them all'

jobs:
  erase-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Erase Infrastructure
        shell: bash
        run: |
            resourceGroup="${{ github.event.inputs.resource-group-name }}"
            if [ "$resourceGroup" = "clear-all" ]; then
              echo "Clearing all..."
            else
              az group delete -n $resourceGroup --yes
            fi
            
