name: Powershell test

on:
  workflow_dispatch:

jobs:
  pwsh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Installing pwsh module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -Verbose
          Update-Module -Name Az -Scope CurrentUser -Force
          Get-Module -Name Az

      - name: Connecting pwsh 
        shell: pwsh
        run: |
          $securePassword = ConvertTo-SecureString ${{ secrets.AZ_CLIENT_SECRET }} -AsPlainText -Force
          $psCredential = New-Object System.Management.Automation.PSCredential(${{ secrets.AZURE_CLIENT_ID }}, $securePassword)
          Connect-AzAccount -ServicePrincipal -Credential $psCredential -Tenant ${{ secrets.AZURE_TENANT_ID }} -SubscriptionId $subscriptionId