name: Powershell test

on:
  workflow_dispatch:

jobs:
  pwsh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Custom Login
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZ_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Installing pwsh module
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -Verbose
          Update-Module -Name Az -Scope CurrentUser -Force
          Get-Module -Name Az

      - name: Connecting pwsh 
        env: 
          USERNAME: ${{ secrets.AZURE_CLIENT_ID }}
          PASSWORD: ${{ secrets.AZ_CLIENT_SECRET }}
        shell: pwsh
        run: |
          $clientId = $env:USERNAME
          $clientSecret = $env:PASSWORD
          $securePassword = ConvertTo-SecureString -String $clientSecret -AsPlainText -Force
          $psCredential = New-Object System.Management.Automation.PSCredential($clientId, $securePassword)
          Connect-AzAccount -ServicePrincipal -Credential $psCredential -Tenant ${{ secrets.AZURE_TENANT_ID }} -SubscriptionId 'c550fb2d-3f43-40b7-9e36-f1d47f436e42'
          Get-AzResourceGroup

    